language: python
sudo: required
dist: trusty

services:
- docker

install:
- docker-compose pull
- docker-compose build

before_script:
- docker-compose up -d

script:
- docker-compose run -e DJANGO_SETTINGS_MODULE=djangodocker.settings.testing --no-deps --rm app bash -c "./scripts/wait-for-prestashop.sh && python manage.py makemigrations; python manage.py migrate; coverage run -m pytest;"

deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master
    skip_cleanup: true
