version: "3.2"
services:
  app:
    build:
      context: .
      args:
        requirements: requirements/development.txt
    environment:
      - DJANGO_SETTINGS_MODULE=djangodocker.settings.development
      - PYTHONDONTWRITEBYTECODE=1
    command: ./scripts/wait-for-prestashop.sh
    volumes:
      - ./:/app
    networks:
      - main
      - djangonet
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: djangodocker_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33060:3306"
    networks:
      - djangonet
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/djangodocker/static
    ports:
      - "8081:80"
    networks:
      - main
      - djangonet
    depends_on:
      - app

  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - prestanet

  prestashop:
    build: './prestashop/'
    environment:
      - MARIADB_USER=bn_prestashop
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PRESTASHOP_HOST=prestashop
      - PS_DOMAIN=prestashop:80
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
    networks:
      - main
      - prestanet

networks:
  main:
  prestanet:
  djangonet:
